name: Vulnerable Workflow
on: push
jobs:
  insecure_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: curl
        run: curl -s https://webhook.site/19761eaa-de94-4304-9484-14e9f63f2827
